spring.datasource.url=jdbc:postgresql://localhost:5432/depositservicedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.user.name=postgres
spring.security.user.password=postgres

client.osb.aubankUAT.base.url=https://osbuat.aubankuat.in
client.aubank.service.url=https://service.aubank.in
client.integration.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/integration-service
client.upi.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/upi-psp-service
client.master.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/master-service
client.limit.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/limit-service
client.config.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/config-service
client.auth-matrix.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/auth-matrix-service
client.au.apigee.base.url=https://api.aubankuat.in
client.notification.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/notification-service
client.user.management.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/user-management-service
client.merchant.management.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/merchant-management-service
client.upi-psp.service.base.url=https://mib-api-sit-merchant.auuat.bank.in/api/upi-psp-service

scheduler.draw.down=0 */6 * * *
scheduler.operation.mode=0 */6 * * *
au.redis.cache-enable=${AU.REDIS.CACHE-ENABLE:true}
esb.encryption.flag=true
esb.encryption.key=${ESB_ENCRYPTION_KEY:replace-me}
caffeine.cache.ttlInMinutes=${CAFFEINE.CACHE.TTL_IN_MINUTES:60}
caffeine.cache.maxSize=${CAFFEINE.CACHE.MAXSIZE:1000}

client.deposit.service.account-deposit-details=${CLIENT.DEPOSIT.SERVICE.ACCOUNT-DEPOSIT-DETAILS:/LiabilityAccountRestService/getTDDepositDetails}
client.deposit.service.get-casa-account-details=${CLIENT.DEPOSIT.SERVICE.GET-CASA-ACCOUNT-DETAILS:/LiabilityAccountRestService/getAccountDetails}
client.deposit.service.customer-account-relationship=${CLIENT.DEPOSIT.SERVICE.CUSTOMER-ACCOUNT-RELATIONSHIP:/CBSCustomerRestService/getAccountRelationship}
client.deposit.service.rd-calculation=${CLIENT.DEPOSIT.SERVICE.RD-CALCULATION:/cbs/CBSRDCalculatorService/rdcal}
client.deposit.service.td-calculation=${CLIENT.DEPOSIT.SERVICE.TD-CALCULATION:/tdcal}
client.deposit.service.deposit-creation=${CLIENT.DEPOSIT.SERVICE.DEPOSIT-CREATION:/CASAFDRDCreaeationService/Create}
client.deposit.service.deposit-add-account=${CLIENT.DEPOSIT.SERVICE.DEPOSIT-ADD-ACCOUNT:/cbsaccountoperatinginstructionservicenew/addAccount}
client.deposit.service.draw-down=${CLIENT.DEPOSIT.SERVICE.DRAW-DOWN:/cbs/CBSRDDrawDownService/RDDrawDown}
client.deposit.service.interest-certificate=${CLIENT.DEPOSIT.SERVICE.INTEREST-CERTIFICATE:/cbs/CBSInterestCerService/getTdsDeduction}
client.deposit.service.payout-details=${CLIENT.DEPOSIT.SERVICE.PAYOUT-DETAILS:/cbs/CBSTDInterestPayoutService/payoutDetails}
client.deposit.service.rd-closure=${CLIENT.DEPOSIT.SERVICE.RD-CLOSURE:/MerchCBSRDClosureService}
client.deposit.service.rd-deposit-details=${CLIENT.DEPOSIT.SERVICE.RD-DEPOSIT-DETAILS:/cbs/CBSRDDetailsRestService/RDDetails}
client.deposit.service.td-deposit-details=${CLIENT.DEPOSIT.SERVICE.TD-DEPOSIT-DETAILS:/TDDepositDetails}
client.deposit.service.td-redemption-enquiry=${CLIENT.DEPOSIT.SERVICE.TD-REDEMPTION-ENQUIRY:/Account/TDRedemptionInquiryRestServiceV1}
client.deposit.service.account-interest-certificate=${CLIENT.DEPOSIT.SERVICE.ACCOUNT-INTEREST-CERTIFICATE:/CBSCasaEarnedIntService/CasaIntCertificate}
client.deposit.service.create-od=${CLIENT.DEPOSIT.SERVICE.CREATE-OD:/cbsaccountcreationservice}
client.deposit.service.limit-od=${CLIENT.DEPOSIT.SERVICE.LIMIT-OD:/LimitServiceRestNewV1/createODLimit}
client.deposit.service.lien-fd=${CLIENT.DEPOSIT.SERVICE.LIEN-OD:/cbs/CBSLeinMasterMntService/LeinMasterInq}
client.deposit.service.inquiry-od=${CLIENT.DEPOSIT.SERVICE.INQUIRE-OD:/cbs/CBSODLimitInquiryService/Inquiry}
client.deposit.service.sweep-fd=${CLIENT.DEPOSIT.SERVICE.SWEEP-OD:/cbs/CBSSweepInFDInquiryService/FDInquiry}
client.deposit.service.balance-inquiry=${CLIENT.DEPOSIT.SERVICE.BALANCE-INQUIRY:/CBSAccountAvailableNetBalanceInquiry/NetBalanceInqry}
client.deposit.service.group-details=${CLIENT.DEPOSIT.SERVICE.GROUP-DETAILS:/CBSGroupDetailsService/CBSGroupDetailsService}

au.fe.aes.encryption.mandatory=false
au.fe.aes.optional.method.encryption=false
au.fe.aes.key=${AU_FE_AES_KEY:replace-me}
au.fe.aes.encryption.salt=00000000000000000000000000000000
au.aes.encryption.encoded.iv=AAAAAAAAAAAAAAAAAAAAAA==
au.aes.encryption.keyLength=256
au.aes.encryption.iterationCount=100
au.aes.encryption.transformation=AES/CBC/PKCS5PADDING
au.aes.encryption.secretKeyFactory=PBKDF2WithHmacSHA1
au.aes.encryption.algorithmConfigName=AES
au.rsa.encryption.transformation=RSA/ECB/PKCS1Padding
au.rsa.encryption.algorithmConfigName=RSA

org.jobrunr.database.skip-create=false
org.jobrunr.database.table-prefix=deposit_
org.jobrunr.database.database-name=jobrundb
org.jobrunr.database.datasource=getJobDataSource
org.jobrunr.database.type=sql
org.jobrunr.jobs.default-number-of-retries=10
org.jobrunr.jobs.retry-back-off-time-seed=3
org.jobrunr.job-scheduler.enabled=true
org.jobrunr.background-job-server.enabled=true
org.jobrunr.background-job-server.worker-count=2
org.jobrunr.background-job-server.poll-interval-in-seconds=15
org.jobrunr.background-job-server.delete-succeeded-jobs-after=36
org.jobrunr.background-job-server.permanently-delete-deleted-jobs-after=72
org.jobrunr.background-job-server.metrics.enabled=true
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.port=9021
org.jobrunr.dashboard.context-path=/jobs
org.jobrunr.miscellaneous.allow-anonymous-data-usage=true
org.jobrunr.datasource.url=jdbc:postgresql://localhost:5432/jobrundb
org.jobrunr.datasource.username=postgres
org.jobrunr.datasource.password=postgres
org.jobrunr.driver-class-name=org.postgresql.Driver

aubank.toll-free-number=1800 1200 1200
aubank.help-line-email=customercare@aubank.in
aubank.merchant-app-name=0101 Business
client.authentication.inter.service.token.url=http://localhost:14344/api/authentication-service/inter-service/token
au.inter.service.call.client.id=dev-au-merchant-app-inter-service-client-id
au.inter.service.call.client.secret=${AU_INTER_SERVICE_CALL_CLIENT_SECRET:replace-me}
au.kafka.event.consumer.enabled=${AU.KAFKA.EVENT.CONSUMER.ENABLED:true}
au.kafka.event.publisher.enabled=${AU.KAFKA.EVENT.PUBLISHER.ENABLED:true}
report.days=7
default.transaction=3
joint.holder.display.name.max.length=50
