spring.application.name=deposit-service-accounts
server.port=13002
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.flyway.baseline-on-migrate=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.lifecycle.timeout-per-shutdown-phase=30s
rest.api.base-path=/api/${spring.application.name}
server.shutdown=graceful
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.forward-headers-strategy=framework
management.endpoints.web.exposure.include=diskSpace,ping,health,auditevents,beans,info,metrics,env,prometheus
management.endpoints.web.base-path=/api/${spring.application.name}
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/api/${spring.application.name}/api-docs/swagger-ui
springdoc.api-docs.path=/${spring.application.name}/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.packages-to-scan=example
spring.data.jpa.repositories.bootstrap-mode=default
spring.jpa.properties.hibernate.format_sql=true
logging.config=classpath:logback-spring.xml
feign.client.config.default.loggerLevel=full
feign.client.config.retry.maxAttempt=3
feign.client.config.retry.interval.milliseconds=100
payments-service.constants.toll-free-key=tollFree
payments-service.constants.toll-free-number=1800 1200 1200
tsd.limit=150000

app.feign.esb.header-map.apiuser=MerchAPIUser
app.feign.esb.header-map.apikey=${APP_FEIGN_ESB_HEADER_MAP_APIKEY:replace-me}
app.feign.esb.header-map.Content-Type=application/json

interest.certificate.folder.path=/templates/interestCertificate
deposit.advice.header.path=/templates/deposit_advice_template/header.html
deposit.advice.footer.path=/templates/deposit_advice_template/footer.html
fixed.deposit.advice.path=/templates/deposit_advice_template/fd_deposit_advice.html
account.interest.certificate.main.content=/templates/account_interest_certificate/account_interest_certificates.html
account.interest.certificate.header.path=/templates/account_interest_certificate/header.html
account.interest.certificate.footer.path=/templates/account_interest_certificate/footer.html
fixed.deposit.advice.conditions=/templates/deposit_advice_template/fd_conditions.html
recurring.deposit.advice.path=/templates/deposit_advice_template/rd_deposit_advice.html
recurring.deposit.advice.conditions=/templates/deposit_advice_template/rd_conditions.html
tax.deposit.advice.path=/templates/deposit_advice_template/tsd_deposit_advice.html
tax.deposit.advice.conditions=/templates/deposit_advice_template/tsd_conditions.html
au.logo.path=classpath:templates/assets/au-logo.png
phone.icon.path=classpath:templates/assets/phone.png
website.icon.path=classpath:templates/assets/website.png
location.icon.path=classpath:templates/assets/location.png
hand.icon.path=classpath:templates/assets/hand.png
email.icon.path=classpath:templates/assets/e-mail.png

od.principle=80%
od.principleValue=80
od.interest=2%
od.interestValue=2
od.intro.question=Need Funds? Use your Fixed Deposits to avail an
od.intro.heading=Instant Overdraft!
od.intro.subheading=Get ${od.principleValue}% of your FD value up to 2cr
od.intro.imageUrl=http://google.com
od.intro.popup[0].heading=Access funds anytime
od.intro.popup[0].subheading=Get money without breaking your FD
od.intro.popup[1].heading=Smart & affordable
od.intro.popup[1].subheading=Pay interest only on what you use (FD rate + ${od.interestValue}%)
od.intro.popup[2].heading=FD keeps growing
od.intro.popup[2].subheading=Earns interest, auto-renews & stays lien-marked
od.intro.popup[3].heading=Spend money your way
od.intro.popup[3].subheading=Transfer money, pay bills or recharge anytime
od.intro.imageUrls[0]=https://sit-ibmb-static.aubankuat.in/odfd/avatar.png
